name: CI - Run API tests

# 1. Trigger the pipeline on specific events
on:
  push:
    branches: [ main ]

#  pull_request:
#    branches: [ main ]

# 2. Define the tasks (jobs) to run
jobs:
  test:
    # Specify the virtual environment machine
    runs-on: ubuntu-latest

    # Sequence of steps executed in this job
    steps:
      # Step 1: Clone your repository code onto the runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up your language runtime (Example: Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install application dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Start Server (background) and wait for health
      - name: Start server
        run: |
           npm start &
           for i in {1..15}; do
           curl -sSf http://localhost:10000/health && break
           sleep 1
           done

       # Step 5: Install Newman
      - name: Install Newman
        run: npm install -g newman

       # Step 6: Run Postman tests with Newman
      - name: Run tests with Newman
        run: newman run CI_Demo_Tests_postman_collection.json -e CI_Demo_Tests_postman_enviroment.json



         

        
